import { WorkMapSchema } from "../../src/index.js";
import { DEMO, EXPERT, GUARDRAILS, LEARNER, STEPS, WORKFLOW, WORKMAP } from "./demo.js";

const q = (v: string | null | undefined) => (v === null || v === undefined ? "null" : `'${v.replaceAll("'", "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const n = (v: number) => String(v);

/** Renders supabase/seed.sql. Validates the Work Map against the contracts first. */
export function renderSeed(): string {
  WorkMapSchema.parse(WORKMAP);
  const org = q(DEMO.orgId);
  const out: string[] = [];
  out.push(`-- GENERATED by \`pnpm seed:gen\` from dev/seed/demo.ts. Do not edit by hand.
-- Demo data (docs/SCHEMA.md "seed.sql"). Runs on \`supabase db reset\`.

insert into orgs (id, name) values (${org}, ${q(DEMO.orgName)});

insert into experts (id, org_id, display_name, language, onet_code)
values (${q(EXPERT.id)}, ${org}, ${q(EXPERT.display_name)}, ${q(EXPERT.language)}, ${q(EXPERT.onet_code)});

insert into learners (id, org_id, display_name, language)
values (${q(LEARNER.id)}, ${org}, ${q(LEARNER.display_name)}, ${q(LEARNER.language)});

insert into workflows (id, org_id, name, description, onet_code)
values (${q(WORKFLOW.id)}, ${org}, ${q(WORKFLOW.name)}, ${q(WORKFLOW.description)}, ${q(WORKFLOW.onet_code)});

-- Pre-confirmed Work Map v1 for the demo fallback.
insert into work_maps (id, org_id, workflow_id, expert_id, version, status, language, json, confirmed_turn_id, published_at)
values (${q(WORKMAP.id)}, ${org}, ${q(WORKFLOW.id)}, ${q(EXPERT.id)}, ${n(WORKMAP.version)}, ${q(WORKMAP.status)}, ${q(WORKMAP.language)},
  ${j(WORKMAP)}, ${q(WORKMAP.confirmed_turn_id)}, now());
`);

  out.push("insert into work_map_steps (id, org_id, work_map_id, key, ordinal, title, decision, reason_quote, reason_quote_en, reason_turn_id, source_label, is_judgment_call, screen_moment, screen_signature) values");
  out.push(
    STEPS.map(
      (s) =>
        `  (${q(s.id)}, ${org}, ${q(WORKMAP.id)}, ${q(s.key)}, ${n(s.ordinal)}, ${q(s.title)}, ${q(s.decision)}, ${q(s.reason?.quote)}, ${q(s.reason?.quote_en)}, ${q(s.reason?.turn_id)}, ${q(s.reason?.source_label)}, ${s.is_judgment_call}, ${j(s.screen_moment)}, ${j(s.screen_signature)})`,
    ).join(",\n") + ";\n",
  );

  out.push("insert into guardrails (id, org_id, work_map_id, key, kind, description, rule_jsonlogic, consequence, quote, quote_en) values");
  out.push(
    GUARDRAILS.map(
      (g) => `  (${q(g.id)}, ${org}, ${q(WORKMAP.id)}, ${q(g.key)}, ${q(g.kind)}, ${q(g.description)}, ${j(g.rule)}, ${j(g.consequence)}, ${q(g.quote)}, ${q(g.quote_en)})`,
    ).join(",\n") + ";\n",
  );

  out.push("-- Evidence: every step and guardrail links to a screen moment and the expert's words.");
  out.push("insert into step_evidence (org_id, work_map_id, step_id, guardrail_id, screen_event_id, transcript_turn_id, t_ms, quote, source_label) values");
  const evidence = [
    ...STEPS.map((s) => `  (${org}, ${q(WORKMAP.id)}, ${q(s.id)}, null, ${q(s.screen_moment.event_ids[0])}, ${q(s.reason!.turn_id)}, ${n(s.screen_moment.t_ms)}, ${q(s.reason!.quote)}, ${q(s.reason!.source_label)})`),
    ...GUARDRAILS.map((g) => {
      const e = g.evidence[0]!;
      return `  (${org}, ${q(WORKMAP.id)}, null, ${q(g.id)}, ${q(e.event_id)}, ${q(e.turn_id)}, ${n(e.t_ms)}, ${q(g.quote)}, ${q(`Sabine, ${clock(e.t_ms)}`)})`;
    }),
  ];
  out.push(evidence.join(",\n") + ";\n");

  out.push("-- Knowledge base for recall_context (full-text search): original German + English.");
  out.push("insert into kb_chunks (org_id, workflow_id, work_map_id, kind, ref_id, content) values");
  out.push(
    [
      ...STEPS.map((s) => `  (${org}, ${q(WORKFLOW.id)}, ${q(WORKMAP.id)}, 'step', ${q(s.id)}, ${q(`${s.key} ${s.title}. ${s.decision}. ${s.reason!.quote} ${s.reason!.quote_en}`)})`),
      ...GUARDRAILS.map((g) => `  (${org}, ${q(WORKFLOW.id)}, ${q(WORKMAP.id)}, 'guardrail', ${q(g.id)}, ${q(`${g.key} ${g.description} ${g.quote} ${g.quote_en}`)})`),
    ].join(",\n") + ";\n",
  );

  out.push(`update workflows set current_workmap_id = ${q(WORKMAP.id)} where id = ${q(WORKFLOW.id)};

-- Teammates sign in by magic link first, then an operator grants them admin (SQL editor, service role):
--   select public.grant_demo_role('you@example.com');            -- admin
--   select public.grant_demo_role('you@example.com', 'manager');
create or replace function public.grant_demo_role(p_email text, p_role text default 'admin')
returns void language plpgsql security definer set search_path = '' as $$
declare uid uuid;
begin
  select u.id into uid from auth.users u where lower(u.email) = lower(p_email);
  if uid is null then
    raise exception 'no auth user with email %; sign in by magic link first', p_email;
  end if;
  insert into public.org_members (org_id, user_id, role) values (${org}, uid, p_role)
  on conflict (org_id, user_id) do update set role = excluded.role;
end $$;
revoke all on function public.grant_demo_role(text, text) from public, anon, authenticated;
`);
  return out.join("\n");
}

function clock(t_ms: number): string {
  const s = Math.floor(t_ms / 1000);
  return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;
}
